name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: skylyrac/blocksds:slim-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Clone ndsx
        run: git clone https://github.com/trustytrojan/ndsx ../ndsx --branch busybox --depth 1

      - name: Install necessary packages
        run: apt update && apt install -y --no-install-recommends build-essential file

      - name: Delete `itoa` and `utoa` declarations in `stdlib.h`
        run: sed -i -E '/^char \*[iu]toa\(.+__picolibc_export;$/d' /opt/wonderful/toolchain/gcc-arm-none-eabi/arm-none-eabi/include/stdlib.h

      - name: Build
        run: bash build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ndsx-busybox
          if-no-files-found: error
          path: ./libbusybox.a
